### ISSUE TITLE
Newtonsoft.Json.JsonConvert.DeserializeObject not working

### ISSUE THREAD

**Issue by theninh** [JasonXuDeveloper/JEngine#326]
try
			{
                string rawData = "{\"Id\":1,\"name\": \"abc\"}";
				
				TestEmptyClass a = JsonConvert.DeserializeObject<TestEmptyClass>(rawData.ToString());
				Debug.LogError("name: " + name);
			}
			catch (Exception ex)
			{
				Debug.LogError("jsonConvert " + ex.Message + " - " + ex.GetType().Name);
                               //Exception has been thrown by the target of an invocation. - TargetInvocationException
			}

public class TestEmptyClass
    {
        public int Id { get; set; }
        public string name { get; set; }
    }

it log exception in catch ("Exception has been thrown by the target of an invocation. - TargetInvocationException").
please tell me fix it :(

**Comment by JasonXuDeveloper** [comment]
For NewtonSoft.JSON and other serialising library that requires a type to deserialise, you need to modify their source code. I.e. the modification I made for LitJson and Protobuf-net, you will need to modify the function when the library deserialise a data to a type, you need to use ILRuntime's ILType.Instantiate to create an instance rather than Activater.CreateInstance, and you will need to do some reflection to set value, also when a field is an Enum defined in HotUpdateScripts, you will need to set an int value during reflection (rather than Enum.Parse). Most importantly, you need CLR redirections for generic functions where its generic parameter is defined in HotUpdateScripts.

It is recommended to go to LitJson's JsonWritter.cs and have a look for the WriteValue part, or go to Protobuf-net's similar function (Serializer.Deserialize) and have a look of how it should properly processed.

Finally, you can go to RegisterCLRRedirection.cs and look for the code how I registered and redirected generic method to make the original function capable for recognising an ILRuntime.ILType as a generic parameter.

**Comment by theninh** [comment]
Thank you sir,
I used ListJson and it solved the above problem.
I want to ask more about JsonProperty hope you answer,
What function in ListJson can I use similar to JsonProperty?
If not, I will study more of your suggestions above.
Have a nice day :D

**Comment by JasonXuDeveloper** [comment]
I think LitJson will convert all the fields defined in a class as a JsonProperty, and if you want to ignore a field, by adding the attribute ```[JsonIgnore]``` would help.

**Comment by theninh** [comment]
I mean 
 string rawData = "{"Id":1,"Name_ENG": "abc"}";
TestEmptyClass b = LitJson.JsonMapper.ToObject<TestEmptyClass>(rawData1);
Debug.log("new name: " + b.new_name);

public class TestEmptyClass
{
public int Id { get; set; }
[JsonProperty("Name_ENG")]
public string new_name { get; set; }
}
LitJson Can do it?




And i saw a new bug
when i build assetBundle -> error -> 

[JEngine Error] System.NullReferenceException: Object reference not set to an instance of an object
  at JEngine.Core.CryptoMgr.AesEncrypt (System.Byte[] toEncryptArray, System.String key) [0x00033] in /Users/theninh/Downloads/JEngine-0.7.2/UnityProject/Assets/Dependencies/JEngine/Core/Manager/CryptoMgr.cs:108 
UnityEngine.Debug:LogError (object)
JEngine.Core.Log:PrintError (object) (at Assets/Dependencies/JEngine/Core/Logger/Log.cs:44)
JEngine.Core.CryptoMgr:AesEncrypt (byte[],string) (at Assets/Dependencies/JEngine/Core/Manager/CryptoMgr.cs:114)
JEngine.Editor.BuildBundles/<>c__DisplayClass0_0/<<BuildAssetBundles>b__0>d:MoveNext () (at Assets/Dependencies/JEngine/Editor/ABTools/BuildBundles.cs:26)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<JEngine.Editor.BuildBundles/<>c__DisplayClass0_0/<<BuildAssetBundles>b__0>d> (JEngine.Editor.BuildBundles/<>c__DisplayClass0_0/<<BuildAssetBundles>b__0>d&)
JEngine.Editor.BuildBundles/<>c__DisplayClass0_0:<BuildAssetBundles>b__0 (string)
JEngine.Editor.BuildBundles:BuildAssetBundles () (at Assets/Dependencies/JEngine/Editor/ABTools/BuildBundles.cs:55)

I find in BuildBundles.cs have 
FileMgr.Delete(dllPath); 
before 
var bytes = FileMgr.FileToByte(dllPath);
                var result = FileMgr.ByteToFile(CryptoMgr.AesEncrypt(bytes, s),
                    DllMgr.GetDllInRuntimePath(ConstMgr.MainHotDLLName));
i comment FileMgr.Delete(dllPath); it worked fine.

**Comment by JasonXuDeveloper** [comment]
```JsonData``` is what you are looking for.

Accordingly, that bug was fixed yesterday, you can either download code from master branch or release page and update the respected code located in your project. I would recommend to download it later today, as there will be another bug fix in about 5 hours

**Comment by theninh** [comment]
oh, Thank You Sir.
Have a nice day 👍

**Comment by JasonXuDeveloper** [comment]
no worries, hope you take care, all the best.
